# Generated by Django 2.0.13 on 2019-06-09 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Func_Tran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_func', models.CharField(max_length=64)),
                ('tipo_funcoes', models.CharField(max_length=2)),
                ('param1', models.IntegerField()),
                ('param2', models.IntegerField()),
                ('compl', models.CharField(max_length=6)),
                ('pont_func', models.IntegerField()),
                ('nome_cont', models.CharField(max_length=128)),
                ('data_cad', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
